#!/usr/bin/env ruby

require 'net/http'

# capture png file
tmpfile = "/tmp/file_upload#{$$}.png"
app = ARGV.shift.to_s
file = ARGV.shift.to_s

if !File.exist?(file) then
  exit
end

data = File.read(file)

# upload
boundary = '----BOUNDARYBOUNDARY----'

HOST = 'gyaile.example.com'
CGI = '/'
UA   = 'Gaile/1.0'

data = <<EOF
--#{boundary}\r
content-disposition: form-data; name="data"; filename="#{File.basename(file)}"\r
\r
#{data}\r
--#{boundary}--\r
EOF

header ={
  'Content-Length' => data.length.to_s,
  'Content-type' => "multipart/form-data; boundary=#{boundary}",
  'User-Agent' => UA
}

Net::HTTP.start(HOST,80){|http|
  res = http.post(CGI,data,header)
  url = res.response.body
  IO.popen("pbcopy","r+"){|io|
    io.write url
    io.close
  }
  system "open #{url}"
}
